### ISSUE TITLE
Chromium based wallet detection

### ISSUE THREAD

**Issue by nrhs05** [syscoin/pali-wallet#263]
I am always having issues getting the bridge sites (new and old) to connect to the Pali app on multiple pcs, as it will continually prompt over and over and never realized that its connected to the site even when it is, also see a fair amount of people in the syscoin support saying the same thing.

It always happens on windows 10, brave/chrome (chromium) and always seems to work fine in firefox. the only thing i can find is:
![image](https://user-images.githubusercontent.com/6243414/189535359-18fedab1-5e81-4ae7-a715-4a58ddc04da5.png)
and 
![image](https://user-images.githubusercontent.com/6243414/189535425-679546e0-7665-47a5-bebc-8b320f441a45.png)

Usually end up using firefox, and telling others to use firefox instead. if you want more info i can try and find some more info.

**Comment by amandagonsalves** [comment]
hey @nrhs05, thanks for reporting. we are looking into bridge/dapp and trezor issues and as soon as we have a new version i'll send here for you to test, probably today or tomorrow 😄

**Comment by amandagonsalves** [comment]
closing for now, i'll reopen when we have the zip file ❤️
