### ISSUE TITLE
[Bug] Minor issue with re-using change address

### ISSUE THREAD

**Issue by nrhs05** [syscoin/pali-wallet#268]
### What happened?

I have a video, which I can upload later if needed. But it is pretty straight forward. Essentially:

One of my addresses, sys1qh6jx34pztsl2mf6tdz0l5hy9mvmfaq3qtpumfu - balance of 0 sys but has 5 previous TXs

Based on UTXO never wanting to use this address again due to the weakening security of an already used address, it should not really be used again if possible. However, after making a TX when pali generated a new change address, it ended up using the above address as my receiving address in Pali address again.

I am assuming it is checking for a 0 balance address, rather than an address with 0 balance and 0 previous tx's?

### Version

1.0.28

### What platform are you using?

Windows

### What browser are you using?

Chrome

### Is this a trezor issue?

No

**Comment by amandagonsalves** [comment]
hi @nrhs05, we are checking into it now, sorry for the late reply, as soon as we have a new version i'll reopen this issue so you can know and test it, thanks for reporting this 😄
