### ISSUE TITLE
Not really a bug, but a feature req

### ISSUE THREAD

**Issue by nrhs05** [syscoin/pali-wallet#3]
Not sure if this is intent and part of design.  When you scroll down in the wallet to view transactions, it collapses the balance and hides it and shows only transactions, that's fine but when you try and use the scroll wheel to go back up and view the balance again you cannot, you have to click the arrow to un-collapse it. Some users might find it a bit annoying, even if its "just a click"

**Comment by claudiovb** [comment]
Hey, @nrhs05 we took into consideration your request and already added it to our sprints at the v2 development of Pali.
So expect updates as we release the new versions!
