### ISSUE TITLE
[Bug] Copying TXID information only copy/pastes part of the TX and it is truncated

### ISSUE THREAD

**Issue by nrhs05** [syscoin/pali-wallet#398]
### What happened?

You can see how it truncates the 3 fields in the address bar on my screenshot, not sure if this is in the list of your fixes that are waiting to be published to be implemented or not, incase it is not i am logging it here. Happens in both full screen and not full screen mode

![image](https://github.com/syscoin/pali-wallet/assets/6243414/f750d462-0180-4ad8-9949-5564172aefb3)

### Version

2.0.0

### What platform are you using?

Windows

### What browser are you using?

Chrome

### Is this a trezor issue?

No

**Comment by claudiovb** [comment]
Thanks a lot for reporting it @nrhs05 !
We implemented a fix on this commit, on our develop branch:
https://github.com/syscoin/pali-wallet/commit/3bf87c1b519817b781ec2a5d53601278d902ee6e

We will be updating it on the Browsers Extension stores by the end of next week along with other fixes. (We will also start creating tags on GitHub with proper changelogs, from this next release and all the next ones so keep posted for it).
