### ISSUE TITLE
[Bug] Switch & Delete networks bug

### ISSUE THREAD

**Issue by eskrano** [syscoin/pali-wallet#424]
### What happened?

Flow:
- connect wallet 
- add another chain lets name it B
- open full screen mode
- switch to syscoin mainnet at full screen mode
- go manage networks at fullscreen
- remove network B
- go back to tab1 & refresh (still see recently deleted network B)
- go back to full screen tab still at syscoin mainnet

Result: out of sync selected network between 2 tabs

ENV: chrome/ mac os

### Version

2

### What platform are you using?

macOS

### What browser are you using?

Chrome

### Is this a trezor issue?

No

**Comment by claudiovb** [comment]
Fix merged to develop:
https://github.com/syscoin/pali-wallet/pull/426
Once final testing is done we will merge it to master and have this updated on Chrome store
