### ISSUE TITLE
[Improvenment] Add bridge.rollux.com to trusted sites list

### ISSUE THREAD

**Issue by eskrano** [syscoin/pali-wallet#430]
### What happened?

<img width="955" alt="image" src="https://github.com/syscoin/pali-wallet/assets/10223123/02016536-45c1-41dd-8899-7547e4d75c25">

### Version

2

### What platform are you using?

macOS

### What browser are you using?

Chrome

### Is this a trezor issue?

No

**Comment by lucasgabrielgsp** [comment]
Closing this issue because we already added rollux bridge in trusted sites list. Thanks!
