### ISSUE TITLE
Trezor pairing is broken

### ISSUE THREAD

**Issue by tfruiz** [syscoin/pali-wallet#59]
During pairing of a Trezor the extension attempts to load

chrome-extension://mgffkfbidihjpoaomajlbgchddlicgpn/trezor-usb-permissions.html

This results in

Your file couldn’t be accessed
It may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND

**Comment by amandagonsalves** [comment]
pls pass me these details:

- os
- pali version
- trezor firmware version
- trezor suite version
- screenshot of the error message
- steps to reproduce the error (if it is reproducible)
- trezor model

it is working fine using pali v1.0.22 with trezor suite latest v22.11 and trezor firmware v1.10.2 or v1.10.5 (latest one) on macos, pls if it is reproducible provide more details so i can find the error

thanks for the report 😄

**Comment by paauserrat** [comment]
Having the same issue with Pali Wallet

**Comment by pauserratgutierrez** [comment]
Will this be fixed?

**Comment by pauserratgutierrez** [comment]
I still can't connect Trezor model T
![image](https://user-images.githubusercontent.com/73240206/157516633-e5242ca5-7967-4dbe-abac-d6e5f9d15da2.png)

**Comment by pauserratgutierrez** [comment]
Trezor model T
os: Windows 10
pali version: v1.0.24
trezor firmware version: v2.4.3
trezor suite version: v22.2.3

**Comment by amandagonsalves** [comment]
thanks, we will check your problem 😄

**Comment by pauserratgutierrez** [comment]
Chrome drops this when I try to connect my wallet
![image](https://user-images.githubusercontent.com/73240206/167261312-e5656c64-4c36-4bb9-ab20-e4d7a3921837.png)

**Comment by pauserratgutierrez** [comment]
> Chrome drops this when I try to connect my wallet
> ![image](https://user-images.githubusercontent.com/73240206/167261312-e5656c64-4c36-4bb9-ab20-e4d7a3921837.png)
> 

After that I closed and opened again and it connected correctly. But the problem persists sometimes

**Comment by amandagonsalves** [comment]
hi @pauserratgutierrez, just so you know, we have this issue solved a while ago, as well as the other reported issues that are already closed, i'll push a new version with all of these issues fixed, sorry for the late reply, i'm closing this issue now and if you have any other problems you can reopen this, thanks for the report 😄
