### ISSUE TITLE
[Issue-019] : Error importing any tokens

### ISSUE THREAD

**Issue by function0xMarki** [syscoin/pali-wallet#618]
### What happened?

It is not possible to import any type of token.

This happens in all chains (EVM) "Rollux, NEVM and others", as well as UTXO.

In this case, UTXO import of the SYSX asset.
![image](https://github.com/user-attachments/assets/d71918a9-f23c-4c6f-994b-d7691bffe43d)
![image](https://github.com/user-attachments/assets/beeddc50-e45f-44f5-87db-68b6230ff7e1)

In this case, import of any type of token that, as shown in the attached image, is in the test wallet.
![image](https://github.com/user-attachments/assets/9882693a-58fd-46c5-9624-ec8dd3ffb978)

![image](https://github.com/user-attachments/assets/35747813-9d0b-4f4d-9501-22d399c3f51f)
![image](https://github.com/user-attachments/assets/c5612705-6897-4947-8b99-e33255342ad9)
![image](https://github.com/user-attachments/assets/2229b973-50ed-4ab7-b9a3-3ad102488527)

> This happens in both mainnet and testnet.

### Version

v3.0.0 QA

### What platform are you using?

macOS

### What browser are you using?

Brave

### Is this a trezor issue?

No

**Comment by lucasgabrielgsp** [comment]
Fixed ✅

**Comment by Potolski** [comment]
Fixed for UTXO, still broken for NEVM
