### ISSUE TITLE
[Bug-016] : Wrong URL construction in UTXO asset

### ISSUE THREAD

**Issue by function0xMarki** [syscoin/pali-wallet#620]
### What happened?

There is a problem in the construction of the blockbook URL to view the asset information.

This problem affects UTXO.

![image](https://github.com/user-attachments/assets/1706e9b1-593f-463a-b768-62f7012e35db)

It has not been possible to test on EVM because it has not been possible to add a token and do such tests, related to https://github.com/syscoin/pali-wallet/issues/618.

### Version

v3.0.0 QA

### What platform are you using?

macOS

### What browser are you using?

Brave

### Is this a trezor issue?

No

**Comment by vieiraricardo** [comment]
Fixed ✅

**Comment by vieiraricardo** [comment]
Fixed ✅

**Comment by function0xMarki** [comment]
> :white_check_mark:  Solved in v.3.0.0.1
