### ISSUE TITLE
[Bug-019] : Trezor can't send transactions on EVM

### ISSUE THREAD

**Issue by function0xMarki** [syscoin/pali-wallet#627]
### What happened?

The Trezor linked accounts does not allow sending transactions on EVM chains.

https://github.com/user-attachments/assets/3e84b0a9-3d14-4a2c-a737-bb9df52b6aef

<img width="568" alt="Captura de pantalla 2024-09-10 a las 3 13 18" src="https://github.com/user-attachments/assets/5d9dc305-6019-40dd-93d1-82bf7d1dc049">

<img width="398" alt="Captura de pantalla 2024-09-10 a las 3 14 55" src="https://github.com/user-attachments/assets/c4f28fea-3796-4bda-a6cb-c9613cb0e2f2">

UTXO works fine.

### Version

v3.0.0 QA

### What platform are you using?

macOS

### What browser are you using?

Brave

### Is this a trezor issue?

No

**Comment by Potolski** [comment]
Fixed for UTXO, still broken for NEVM

**Comment by function0xMarki** [comment]
:x:  NOT Solved :: The issue has been resolved for EVM, but has carried over into UTXO.

**Comment by function0xMarki** [comment]
:x:  NOT Solved :: The issue has been resolved for EVM, but has carried over into UTXO.

### EVM Solved
<img width="399" alt="Captura de pantalla 2024-09-12 a las 16 04 19" src="https://github.com/user-attachments/assets/ea874acd-b978-4b4d-b3c0-65445aaf079a">

<img width="301" alt="Captura de pantalla 2024-09-12 a las 16 04 40" src="https://github.com/user-attachments/assets/59d98960-77f4-4065-a3de-8e077cfce0ae">

<img width="346" alt="Captura de pantalla 2024-09-12 a las 16 05 56" src="https://github.com/user-attachments/assets/e0ed68c5-0712-4329-b70b-90c7ea56dd08">

### UTXO
<img width="401" alt="Captura de pantalla 2024-09-12 a las 16 02 15" src="https://github.com/user-attachments/assets/5389a8d5-e385-4ef4-a094-d75043a05fc2">

<img width="572" alt="Captura de pantalla 2024-09-12 a las 16 02 32" src="https://github.com/user-attachments/assets/e81c3354-be63-4354-bc21-7134ea0c21e1">

**Comment by function0xMarki** [comment]
> :white_check_mark: Solved in v3.0.0.1
