### ISSUE TITLE
[Bug-020] : Ledger connection not working

### ISSUE THREAD

**Issue by function0xMarki** [syscoin/pali-wallet#628]
### What happened?

Ledger connection not working.
Unable to link using UTXO or EVM.

https://github.com/user-attachments/assets/f85583c4-3d79-44b6-828f-0b362092b616

<img width="572" alt="Captura de pantalla 2024-09-10 a las 3 30 43" src="https://github.com/user-attachments/assets/8aab2d22-cae0-487b-9aa5-10c4a0529a5c">

### Version

v3.0.0 QA

### What platform are you using?

macOS

### What browser are you using?

Brave

### Is this a trezor issue?

No

**Comment by function0xMarki** [comment]
Tested in v3.0.0.1
Same problem.

<img width="577" alt="Captura de pantalla 2024-09-12 a las 16 24 22" src="https://github.com/user-attachments/assets/c4b941f6-1e90-4c41-9dbf-acfb1e3140f3">

**Comment by Potolski** [comment]
Issue happens when user don't select correct network before performing a transaction. 

Quick reminder that the SYScoin app is not available at the ledger store and needs to be built using this repo  https://github.com/osiastedian/ledger-app-syscoin/tree/ledger-merged-develop
