### ISSUE TITLE
[Bug-021] : Error due to exceeding balance, permanently blocking sending transactions

### ISSUE THREAD

**Issue by function0xMarki** [syscoin/pali-wallet#629]
### What happened?

In Pali Wallet v3, a critical bug has been identified that affects the ability to send transactions when a user attempts to send an amount exceeding the total available balance (amount + fee).

This issue results in a persistent blocking of the transaction functionality on the current chain, even if the user later adjusts the amount correctly for future transactions.

https://github.com/user-attachments/assets/f3a7e029-08ec-4b62-bef4-f7e87b56f634

<img width="566" alt="Captura de pantalla 2024-09-10 a las 3 09 31" src="https://github.com/user-attachments/assets/9ab0dbc0-7859-4a7c-a231-f66cbd844dde">

> Problem description:

If a user sets an amount greater than the total available balance (including fees), Pali displays an error that prevents the transaction from being sent.

From this point, the error becomes persistent. Even if the user tries to initiate new transactions with correct amounts that do not exceed their balance, Pali continues to display the same error.

This issue affects all accounts, even when switching between them, keeping the ability to send transactions blocked.

> There are two ways for the user to resolve this problem:

- Disabling and re-enabling the Pali Wallet extension restores normal functionality.
- Switching to a different chain from the one in use when the error occurred, and then switching back to the original chain, also restores the ability to send transactions.

It is important to address this issue to prevent users from experiencing transaction blocks, which could lead to frustration and a negative user experience.

### Version

v3.0.0 QA

### What platform are you using?

macOS

### What browser are you using?

Brave

### Is this a trezor issue?

No

**Comment by Potolski** [comment]
2 questions:
1. How did you set a higher number that the available amount?
2. Why did you try to send a transaction from the same account it is from? (in the video you pasted the account's address in the receiver, I assume you can't send a transaction to yourself, right?)

**Comment by function0xMarki** [comment]
> 1. How did you set a higher number that the available amount?
 
 -- You cannot set an amount higher than your balance, but you can set an amount very close to your balance that (amount + fee) exceeds your balance._

> 2. Why did you try to send a transaction from the same account it is from? (in the video you pasted the account's address in the receiver, I assume you can't send a transaction to yourself, right?)

-- It doesn't matter who the recipient is.
It doesn't matter which recipient.
I used the same source and destination account to make it easier to avoid running out of funds in the test wallet.
But the tests have been carried out with different recipients. The error occurs regardless of the recipient. You cannot send any transaction to any destination, of any amount.

**Comment by function0xMarki** [comment]
> Partially resolved, but a new bug detected

The initial problem has been corrected, but it has triggered a new malfunction.

Previously, the system only allowed users to send an amount exceeding their balance if the amount being sent was very close to the total balance limit. If the amount to be sent plus the fee exceeded this limit, an error occurred that prevented new transactions from being sent, even if the amount was corrected.

**Current behavior:**
Now, if you exceed the amount to be sent and receive the same error, it is possible to send transactions after correcting the balance excess.

**New issue:**
After the correction, the balance verification system is not working properly, allowing users to input an amount that directly exceeds the available balance. In the provided videos, it is observed that:

1. The system marks the amount as valid (green checkmark) even when the amount exceeds the maximum balance.
2. The system allows the user to attempt sending the transaction, although it throws an error afterward.
3. After correcting the amount, the new corrected transaction can now be sent, which was not possible before.

This indicates that the balance validation needs to be reviewed to prevent users from entering amounts higher than their available balance.

https://github.com/user-attachments/assets/f2116fc7-0e96-4f3d-97df-ed9d4888788e

https://github.com/user-attachments/assets/943ddba1-1013-4906-959f-4031633c8a81
