### ISSUE TITLE
Regarding Workflow of script

### ISSUE THREAD

**Issue by harshwardhanedu** [syscoin/pali-wallet#64]
Can i know the script working and flow how it workes??

**Comment by amandagonsalves** [comment]
hi @harshwardhanedu, what exactly do you want to know? we are happy to show you how everything works in pali and we are working on some diagrams to make it easier in the future, but any question more specific pls send here and we will help you 😄

**Comment by harshwardhanedu** [comment]
I am trying make a clone of it and unable to run it at my system

**Comment by amandagonsalves** [comment]
oh ok, if that's it you can follow the steps described in [pali documentation](https://docs.paliwallet.com/) and [pali readme](https://github.com/syscoin/pali-wallet/blob/master/README.md)

you need to have node and yarn installed in your machine

for pali v1 using chrome:
- clone pali repo
- open pali directory
- for pali v1, type `cd extension` and follow to the next step, for v2 you can just follow to the next step
- run `yarn` to install the dependencies
- `yarn dev:chrome`
- open chrome
- go to **chrome://extensions**
- enable developer mode
- click on **load unpacked**
- choose the **chrome** folder inside `pali-wallet/extension/extension`

hope it solves your problem, any more questions send to us

**Comment by harshwardhanedu** [comment]
Thank you 😊
