### ISSUE TITLE
[UX-011] : Strange behavior in the faucet's advertising panel

### ISSUE THREAD

**Issue by function0xMarki** [syscoin/pali-wallet#655]
### What happened?

In the new Canary 3.0.1 update, which restores the faucet functionality removed in the previous version, an unexpected behavior has been detected in the initial announcement panel about the faucet.

When the user opens their EVM account in Pali Wallet for the first time, the large announcement panel appears correctly, and after closing it, it moves to a more discreet version at the bottom of the account information. However, the panel reappears in its full size each time Pali is minimized, even though the user has already closed it previously, forcing them to close it repeatedly.

Additionally, the close button of the panel does not respond reliably, as it closes randomly after several attempts, displaying erratic behavior.

https://github.com/user-attachments/assets/29ffd19b-12df-4cb2-bc56-5c4409352e39

### Version

v3.0.1 Canary

### What platform are you using?

macOS

### What browser are you using?

Brave

### Is this a trezor issue?

No

**Comment by lucasgabrielgsp** [comment]
Fixed ✅
