### ISSUE TITLE
My Sys are no longer in my wallet

### ISSUE THREAD

**Issue by LaT27** [syscoin/pali-wallet#68]
Hello everyone,

Yesterday, I made a transaction between 8 and 9 pm (UTC), from Binance to Paliwallet, the Syscoin arrived fast, but, When I have checked again, they are not there.

The problem is as follows: Paliwallet gave me a new wallet address when I sent the Syscoins from Binance, and checking in "https://blockbook.elint.services/" this address is not associated with my wallet or any of the accounts I have created.

**This is the transaction from Binance:**

**Adress:** sys1q42p3em7kpcrek4k93u7lkeqmp5vsxm4rhqjp5l

**TxID:** e3a5ebcd3577cfda7231c9f8e81dfbe46ae6884b5deafde2b21018f34028aa31

**And this is my Palliwalet:**

https://blockbook.elint.services/xpub/zpub6rE2tjyanmhGSPB4sFauMHt4Ca1aCqACxusdAJFk4AqP6YHbzw7NY2jYS7YuGVbJ7phdyvfeY7Yen9MBxj9ENsNfKA1h2gvTSppDBNNoYu7

I created a ticket in the official syscoin discord yesterday, to report the problem and try to find a solution, that's why several transactions appear in XPUB and the admins told me that this problem had already occurred in previous versions of Paliwallet, it should be clarified that at the time of making the transaction, I had the latest update (1.0.24) and I use the extension in google chrome.

In advance, thank you very much

**Comment by sidhujag** [comment]
Hi @LaT27 how did you create the address sys1q42p3em7kpcrek4k93u7lkeqmp5vsxm4rhqjp5l? This is not a part of your xpub that I can see.

**Comment by LaT27** [comment]
Hi @sidhujag!!

When I went to make the withdraw from Binance, the address "sys1q42p3em7kpcrek4k93u7lkeqmp5vsxm4rhqjp5l" was generated to me when I clicked on the "Receive" button.  

I could see how the SYS got to the wallet, the number 42 was there, however as I say, when I saw the wallet again they were gone.

I restarted the wallet with the seed phrase when this happened, and then that's when I started looking for help with the team from discord

**Comment by LaT27** [comment]
Yes, the "receive" button in Pali.

When I made the withdrawal, I only had one account, the discord team also asked me to create some extra accounts, but the SYS were not there either.

**Comment by sidhujag** [comment]
im not sure then as it seems the address was not created with pali if its not in the xpub.. ive never seen an account not in the xpub.. you can try to do some txs to see if it "shows up" if its passed the derivation window and maybe is the early bug we found where addresses were created just outside the window and show up after you create some new addresses and it gets the missing address within the window

**Comment by LaT27** [comment]
@sidhujag What is a txs?

**Comment by sidhujag** [comment]
i mean try to send yourself some transactions to generate more addresses to increase the derivation window
