### ISSUE TITLE
Feature Request: Ability to bridge between Syscoin <> NEVM in Pali

### ISSUE THREAD

**Issue by LucidLunacy** [syscoin/pali-wallet#8]
Simple Bridge functionality between Syscoin and NEVM. This would include a button on the main page that when clicked loads another page that confirms the amount of Syscoin/token that the user wants to bridge to/from the NEVM chain. The user would then confirm they want to cross the bridge with the input information. The bridging process would then begin running in the background, with a graphical representation of what stage it is at. The wallet should automatically create and sign the bridge transactions without requiring user input besides the first "I confirm I want to bridge this sys/token to/from NEVM". This would make it far easier for users to bridge between Syscoin and NEVM, rather than having to use the bridge dApp and taking the time and effort to follow all the steps.

**Comment by amandagonsalves** [comment]
@LucidLunacy this is a little more complex and our backlog is full already, but it is a great idea and sure we will put on our todo list after launching v2 (or before, if we have time), thank you for your suggestion (:
