### ISSUE TITLE
Feature Request: Send to... functionality in right-click menu

### ISSUE THREAD

**Issue by LucidLunacy** [syscoin/pali-wallet#9]
When a user selects text in their browser the extension should check if it is a viable address, if it is then an entry should be added to the right click menu. For example, Pali Wallet Send to... . After the user clicks this Pali wallet will then open on a page with a selection of icons + names of which blockchain they would like to send the transaction on (Syscoin, Bitcoin, Matic etc). Once this has been selected they will be taken to the relevant sending page to complete the transaction.

**Comment by amandagonsalves** [comment]
hi @LucidLunacy, i guess i didn't really get how you imagine this feature, could you send some more examples to specify better? we are implementing new features so maybe this one already has been implemented (if it is what i'm thinking about), but pls specify maybe with some images or steps and sure we can try to put it in the code (:

**Comment by LucidLunacy** [comment]
![pali](https://user-images.githubusercontent.com/11958320/150503497-98b01393-fd2b-4457-a00c-b2756548bdf3.png)

Sure, it would be like in the attached image.
1. User selects and right clicks the text with an address.
2. User clicks "Pali Wallet | Send to... address".
3. Pali opens with a selection of the networks that use this address format, the user selects which network to use.
4. Pali then opens the Send page for that specific network with the address already added.

This means when users want to send to a specific address they don't need to copy the address, open pali, select the network, select send, paste the address then input the amount to send, they will only need to right click the address, choose send, select the network then input the amount to send.

Hope that makes better sense!
